#Esta configuración puede estar controlada por CONFIG SERVER

###Relacionado a Spring - Hibernate

spring:  
  profiles:
     active: dev
     
  aop:
    proxy-target-class: false
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pyme_erp_seguridad
    username: root
    password: 1234

  jpa:    
    properties:
      hibernate:                             
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        naming_strategy:  org.hibernate.cfg.DefaultNamingStrategy
        #naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQLDialect        
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
        show_sql: true
        format_sql: true          
        packagesToScan: pe.jaav.sistemas.seguridadgeneral.model
     
###Relacionado al despliegue         
---
spring:
  profiles: dev
  application:
    name: seguridadDev
    
server:
  port: ${vcap.application.port:7071}
    
---
spring:
  profiles: local
  application:
    name: seguridadLocal    
           
server:
  port: ${vcap.application.port:8071}
            
#eureka:

#  client:  
#      serviceUrl:
#        defaultZone:  http://localhost:8002/eureka/  
#  instance:
#    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
#          